# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Get files
      - name: Get files
        run: |
          echo $(ls -la)
          echo $(pwd)

      # Runs a set of commands using the runners shell
      - name: Build docker image
        run: |
          echo Add other actions to build
          docker build -t qwerty .
          
      - name: Run docker image
        run: |
          echo "Running docker container.........."
          docker run -v "$(pwd)"/output:/home/ci/project/artefact -i qwerty
        env:
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}
          EXPO_KEY_JKS: ${{ secrets.EXPO_KEY_JKS }}

      # Show built files
      - name: Show build output files
        run: |
          echo $(ls output)
          echo $(ls)
        
