# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux, X64, default]
    # runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Show the release version
        run: |
          echo "Version of this release"
          echo ${{ steps.package-version.outputs.current-version}}

      - name: Install deps for Ubuntu
        run: |
          sudo apt install -y curl
          sudo apt install -y default-jdk
          sudo curl -sL https://deb.nodesource.com/setup_16.x | sudo bash
          sudo apt install -y nodejs

      - name: Install deps for node
        run: |
          sudo npm i -g yarn
          sudo yarn global add http-server
          sudo yarn global add expo-cli
          sudo yarn global add turtle-cli

      - name: Build and integrate FT8 library
        run: |

          # Install emsdk for building FT8 library

          # Save a point where I was
          CURR=`pwd`

          sudo apt update
          sudo apt install -y git
          if [ -d "/app" ]
          then
          rm -rf /app
          fi
          mkdir /app
          cd /app
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          git pull

          apt install -y python3
          apt install -y xz-utils
          apt install -y lbzip2

          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

          # Go back to the point where I was
          cd $CURR

          cd ft8_lib

          # Build encoder
          emcc gen_ft8.c ft8/constants.c ft8/text.c ft8/pack.c ft8/encode.c ft8/crc.c common/wave.c -lm -o encoder.wasm -sEXPORTED_FUNCTIONS="['_get_audio_buffer', '_initialize_audio_buffer', '_customFwrite', '_gen_ft8']" --no-entry

          # Build decoder 
          emcc decode_ft8.c fft/kiss_fftr.c fft/kiss_fft.c ft8/decode.c ft8/encode.c ft8/crc.c ft8/ldpc.c ft8/unpack.c ft8/text.c ft8/constants.c common/wave.c -lm -o decoder.wasm -sEXPORTED_FUNCTIONS="['_get_audio_buffer', '_decode_ft8', '_get_msgs_count', '_get_msg_by_index', '_initialize_audio_buffer', '_get_i0', '_get_i50', '_get_i100', '_get_i150', '_get_time_by_message_id', '_get_freq_by_message_id', '_get_text_by_message_id']" --no-entry

          # Convert wasm(s) byte array
          node wasm2js.js encoder.wasm
          node wasm2js.js decoder.wasm

          cd ..

          echo "export const encode_ft8_code=[$(cat ft8_lib/encoder.txt)]" > encode_ft8_code_external.js
          echo "export const decode_ft8_code=[$(cat ft8_lib/decoder.txt)]" > decode_ft8_code_external.js


      - name: Install prject deps
        run: |
          yarn install
          expo export --dev --public-url http://127.0.0.1:8000
          (sleep 2; echo y;) | expo prebuild

          if [ -f "key.jks" ]
          then
          rm key.jks
          fi

          touch key

          printf "${{secrets.EXPO_KEY_JKS}}" | base64 -d > "$(pwd)/key.jks"

          npx http-server -p 8000 dist &
          
          sudo EXPO_ANDROID_KEYSTORE_PASSWORD="${{secrets.EXPO_ANDROID_KEYSTORE_PASSWORD}}" EXPO_ANDROID_KEY_PASSWORD="${{secrets.EXPO_ANDROID_KEY_PASSWORD}}" turtle build:android \
          --type apk --keystore-path "$(pwd)/key.jks" \
          --keystore-alias "${{secrets.EXPO_KEYSTORE_ALIAS}}" --allow-non-https-public-url \
          --public-url http://127.0.0.1:8000/android-index.json


      - name: Get built APK
        run: |
          echo "CONTENT OF THE EXPO_APP: $(ls /root/expo-apps)"

          sudo mv "/root/expo-apps/$(sudo ls -la /root/expo-apps/ |grep .apk |awk '{print $9}')" FT8Shack.apk

          echo "1: $(sudo ls -la /root/expo-apps/)"
          echo "2: $(sudo ls -la /root/expo-apps/ |grep .apk |awk '{print $9}')"

          if [ -d /root/expo-apps ]
          then
            sudo rm -rf /root/expo-apps/*
          fi




      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ steps.package-version.outputs.current-version}}
          body: |
            Release ${{ steps.package-version.outputs.current-version}}

            ${{ github.event.head_commit.message }}
          draft: true
          prerelease: false
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./FT8Shack.apk
          asset_name: FT8Shack.apk
          asset_content_type: application/vnd.android.package-archive
      - name: Publish release
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}
        
