# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux, X64]
    # runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Show the release version
        run: |
          echo "Version of this release"
          echo ${{ steps.package-version.outputs.current-version}}

      - name: Install deps for Ubuntu
        run: |
          sudo apt install -y curl
          sudo apt install -y default-jdk
          sudo curl -sL https://deb.nodesource.com/setup_16.x | sudo bash
          sudo apt install -y nodejs

      - name: Install deps for node
        run: |
          sudo npm i -g yarn
          sudo yarn global add http-server
          sudo yarn global add expo-cli
          sudo yarn global add turtle-cli

      - name: Install prject deps
        run: |
          yarn install
          expo export --dev --public-url http://127.0.0.1:8000
          (sleep 2; echo y;) | expo prebuild

          if [ -f "key.jks" ]
          then
          rm key.jks
          fi

          touch key

          printf "${{secrets.EXPO_KEY_JKS}}" | base64 -d > "$(pwd)/key.jks"
          echo "Length of the key jks"
          echo "$(cat key.jks | awk '{print length}')"

          npx http-server -p 8000 dist &
          
          sudo EXPO_ANDROID_KEYSTORE_PASSWORD="${{secrets.EXPO_ANDROID_KEYSTORE_PASSWORD}}" EXPO_ANDROID_KEY_PASSWORD="${{secrets.EXPO_ANDROID_KEY_PASSWORD}}" turtle build:android \
          --type apk --keystore-path "$(pwd)/key.jks" \
          --keystore-alias "${{secrets.EXPO_KEYSTORE_ALIAS}}" --allow-non-https-public-url \
          --public-url http://127.0.0.1:8000/android-index.json

      - name: List files
        run: |
          echo $(ls)

      - name: Get built APK
        run: |
          echo "CONTENT OF THE EXPO_APP: $(ls /root/expo-apps)"

          sudo mv "/root/expo-apps/$(sudo ls -la /root/expo-apps/ |grep .apk |awk '{print $9}')" FT8Shack.apk

          echo "1: $(sudo ls -la /root/expo-apps/)"
          echo "2: $(sudo ls -la /root/expo-apps/ |grep .apk |awk '{print $9}')"

          if [ -d /root/expo-apps ]
          then
            sudo rm -rf /root/expo-apps/*
          fi




      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ steps.package-version.outputs.current-version}}
          body: |
            Release ${{ steps.package-version.outputs.current-version}}

            ${{ github.event.head_commit.message }}
          draft: true
          prerelease: false
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./FT8Shack.apk
          asset_name: FT8Shack.apk
          asset_content_type: application/vnd.android.package-archive
      - name: Publish release
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}
        
